# Ours Q
defaults:
  - _self_
  - compression: umbrella_sh

hydra:
  run:
    # output directory for results
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}-${run.name}

run:
  # wandb config: group, run name, tags
  group: "rank_sum_choices"
  name: "run"
  tags: ""

  # don't set manually, will be replaced at runtime
  wandb_url: null

  test_iterations:
    [1000, 2000, 5000, 7000, 10000, 12000, 15000, 17000, 20000, 25000, 30000]
  save_iterations: [7000, 10000, 20000, 30000]
  checkpoint_iterations: []
  start_checkpoint: null

  compress_iterations: [7000, 10000, 20000, 30000]

  # use spherical harmonics in optimization
  use_sh: true

  # throws away any command-line output
  quiet: false

  # hide progress bar
  no_progress_bar: true

  log_nb_loss_interval: 100

  log_training_report_interval: 500

  # pretty slow to compute, only turn on when needed
  test_lpips: false

debug:
  debug_from: -1
  detect_anomaly: false

dataset:
  sh_degree: 3
  source_path: ""
  model_path: ""
  images: "images"
  resolution: -1
  white_background: false
  data_device: "cuda"
  eval: true

optimization:
  iterations: 30000

  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000

  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001

  percent_dense: 0.1

  lambda_dssim: 0.2

  # 3DGS default: 100
  densification_interval: 1000
  densify_from_iter: 500
  densify_until_iter: 15000

  # 3DGS default: 0.0002
  densify_grad_threshold: 0.00007

  # 3DGS default: 1000
  opacity_reset_interval: 10000000

  # 3DGS default: 0.005
  densify_min_opacity: 0.1

  random_background: false

neighbor_loss:
  # set to 0 to disable neighbor loss
  lambda_neighbor: 1.0

  normalize: false
  activated: false

  # "mse" or "huber"
  loss_fn: "huber"

  blur:
    kernel_size: 5
    sigma: 3.0

  weights:
    xyz: 0.0
    features_dc: 0.0
    features_rest: 0.0

    # not used: let individual Gaussians die out if they wish
    opacity: 1.0
    scaling: 0.0
    rotation: 10.0

sorting:
  enabled: true
  normalize: true
  activated: true
  shuffle: true

  improvement_break: 0.0001

  weights:
    xyz: 1.0
    features_dc: 1.0
    features_rest: 0.0
    opacity: 0.0
    scaling: 1.0
    rotation: 0.0

pipeline:
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false

gui_server:
  ip: "127.0.0.1"
  port: 6009

wandb_debug_view:
  view_enabled: false
  save_hist: false

  view_id: 100
  interval: 500

local_window_debug_view:
  enabled: false
  interval: 10
  view_id: 100
